### ISSUE TITLE
Video not supported .m3u8 in Windows App

### ISSUE THREAD

**Issue by HAFIZkhan-source** [jakky1/video_player_win#8]
We are trying to integrate a video play feature in our windows app. Other videos are playing but the issue Is .m3u8 video is not working. We also tested with k-lite codec pack

**Comment by jakky1** [comment]
Duplicate issue #5 

Yes, k-lite codec & this package doesn't support m3u8.
Maybe will support in the future, maybe in 3 months. (but not guaranteed)

**Comment by MarcusCheung00** [comment]
> Duplicate issue #5
> 
> Yes, k-lite codec & this package doesn't support m3u8. Maybe will support in the future, maybe in 3 months. (but not guaranteed)

is there any update?

**Comment by jakky1** [comment]
I found a new package "media_kit" published 2 months ago. You can try it instead.
Although it use ffmpeg library so cause a large app size (~40MB)

I have no idea how to solve this issue with Microsoft Media Foundation,
since I cannot avoid audio/video discontinuous between videos,
so in fact I intended to solve this issue with ffmpeg too.
But since there is another similar package published,
I currently have no reason to publish another similar one.

**Comment by MarcusCheung00** [comment]
> I found a new package "media_kit" published 2 months ago. You can try it instead. Although it use ffmpeg library so cause a large app size (~40MB)
> 
> I have no idea how to solve this issue with Microsoft Media Foundation, since I cannot avoid audio/video discontinuous between videos, so in fact I intended to solve this issue with ffmpeg too. But since there is another similar package published, I currently have no reason to publish another similar one.

is good to know that "media_kit" is using ffmpeg.
in windows env, ffmpeg actually a great solution.

**Comment by jakky1** [comment]
@HAFIZkhan-source,

Now can play .m3u8 url with new version `3.0.0`.
Please give it a try ~
